# Generated by Django 3.2.8 on 2021-10-12 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantprofilemodel',
            name='is_guest',
            field=models.BooleanField(default=False),
        ),
    ]
