# Generated by Django 3.2.8 on 2021-10-12 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_alter_boilerroommodel_apartment'),
        ('users', '0002_tenantprofilemodel_is_guest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenantprofilemodel',
            name='room',
        ),
        migrations.AddField(
            model_name='tenantprofilemodel',
            name='room',
            field=models.ManyToManyField(blank=True, help_text='Assigned rooms', related_name='tenants', related_query_name='tenant', to='properties.RoomModel'),
        ),
    ]
