# Generated by Django 3.2.8 on 2021-10-13 12:17

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20211012_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownerprofilemodel',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, default='', max_length=128, region=None),
        ),
    ]
