# Generated by Django 3.2.8 on 2021-10-13 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_ownerprofilemodel_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownerprofilemodel',
            name='logo',
            field=models.ImageField(blank=True, default='', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='providerprofilemodel',
            name='logo',
            field=models.ImageField(blank=True, default='', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='staffprofilemodel',
            name='logo',
            field=models.ImageField(blank=True, default='', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='tenantprofilemodel',
            name='logo',
            field=models.ImageField(blank=True, default='', null=True, upload_to=''),
        ),
    ]
