# Generated by Django 3.2.8 on 2021-10-13 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20211013_1043'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tenantprofilemodel',
            old_name='room',
            new_name='rooms',
        ),
    ]
