# Generated by Django 3.2.8 on 2021-10-22 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_rename_room_tenantprofilemodel_rooms'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantprofilemodel',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tenants', related_query_name='tenant', to='users.ownerprofilemodel'),
        ),
    ]
