# Generated by Django 3.2.8 on 2021-10-22 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_tenantprofilemodel_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantprofilemodel',
            name='access_link',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
