# Generated by Django 3.2.8 on 2021-10-25 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_tenantprofilemodel_password_reset_needed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantprofilemodel',
            name='password_reset_needed',
            field=models.BooleanField(default=True),
        ),
    ]
