# Generated by Django 3.2.8 on 2021-10-13 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_buildingmodel_address'),
        ('devices', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analoguethermostatmodel',
            name='status',
        ),
        migrations.AlterField(
            model_name='analoguethermostatmodel',
            name='pin_num',
            field=models.SmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9)], help_text='pin connection index', null=True),
        ),
        migrations.AlterField(
            model_name='smartthermostatmodel',
            name='zone',
            field=models.ForeignKey(blank=True, help_text='Related property Heating Zone', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='smart_thermostats', related_query_name='smart_thermostat', to='properties.zonemodel'),
        ),
    ]
