# Generated by Django 3.2.8 on 2021-10-13 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_auto_20211013_0755'),
    ]

    operations = [
        migrations.AddField(
            model_name='boilermodel',
            name='model',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='boilermodel',
            name='health_status',
            field=models.CharField(choices=[('PEN', 'Pending'), ('EXC', 'Excelent'), ('ATN', 'Attention'), ('ERR', 'Error!')], default='', help_text="Boiler's system health status", max_length=3),
        ),
        migrations.AlterField(
            model_name='boilermodel',
            name='type',
            field=models.CharField(choices=[('TKL', 'Tankless'), ('CTR', 'Castiron'), ('CMB', 'Combintaion')], default='', max_length=3),
        ),
    ]
