# Generated by Django 3.2.8 on 2021-10-13 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_auto_20211013_0800'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensormodel',
            name='boiler',
        ),
        migrations.RemoveField(
            model_name='smartthermostatmodel',
            name='status',
        ),
        migrations.AlterField(
            model_name='ioniqcontrollermodel',
            name='load_type',
            field=models.CharField(choices=[('PMP', 'Pump'), ('ZVL', 'Zone Valves')], default='', max_length=3),
        ),
        migrations.AlterField(
            model_name='sensormodel',
            name='pin_num',
            field=models.SmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9)], help_text='PIN number used with Controller connection', null=True),
        ),
        migrations.AlterField(
            model_name='sensormodel',
            name='type',
            field=models.CharField(choices=[('SPL', 'Supply'), ('RTN', 'Return'), ('PRS', 'Pressure')], default='', max_length=3),
        ),
    ]
