# Generated by Django 3.2.8 on 2021-10-13 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_remove_zonemodel_connection_type'),
        ('devices', '0005_auto_20211013_0807'),
    ]

    operations = [
        migrations.AddField(
            model_name='ioniqcontrollermodel',
            name='building',
            field=models.ForeignKey(help_text='Place of installation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ioniq_controllers', related_query_name='ioniq_controller', to='properties.buildingmodel'),
        ),
    ]
