# Generated by Django 3.2.8 on 2021-10-20 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0007_alter_zipcodemodel_todays_temp'),
        ('devices', '0007_ioniqcontrollermodel_model_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimpleSwitchModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('ONN', 'ON'), ('OFF', 'OFF')], default='OFF', max_length=3)),
                ('zone', models.ForeignKey(help_text='Related Heating Zone', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='simple_switches', related_query_name='simple_switch', to='properties.zonemodel')),
            ],
            options={
                'verbose_name': 'Analogue thermostat',
                'verbose_name_plural': 'Analogue thermostats',
                'ordering': ['-created_at'],
            },
        ),
    ]
