# Generated by Django 3.2.8 on 2021-10-20 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0008_simpleswitchmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='simpleswitchmodel',
            options={'ordering': ['-created_at'], 'verbose_name': 'Heat wwitch', 'verbose_name_plural': 'Heat wwitchers'},
        ),
        migrations.AddField(
            model_name='simpleswitchmodel',
            name='pin_num',
            field=models.SmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9)], help_text='pin connection index', null=True),
        ),
        migrations.AlterField(
            model_name='simpleswitchmodel',
            name='status',
            field=models.CharField(choices=[('ON', 'ON'), ('OFF', 'OFF')], default='OFF', max_length=3),
        ),
    ]
