# Generated by Django 3.2.8 on 2021-10-21 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0009_auto_20211020_1326'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='simpleswitchmodel',
            options={'ordering': ['-created_at'], 'verbose_name': 'Heat switch', 'verbose_name_plural': 'Heat switchers'},
        ),
        migrations.AddField(
            model_name='smartthermostatmodel',
            name='pin_num',
            field=models.SmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9)], help_text='pin connection index', null=True),
        ),
    ]
