# Generated by Django 3.2.8 on 2021-10-21 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0010_auto_20211021_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='analoguethermostatmodel',
            name='status',
            field=models.CharField(choices=[('ON', 'ON'), ('OFF', 'OFF')], default='OFF', max_length=3),
        ),
    ]
