# Generated by Django 3.2.8 on 2021-10-22 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0012_alter_analoguethermostatmodel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='boilermodel',
            name='shutdown_temp',
            field=models.IntegerField(blank=True, help_text='Warm weather shutdown setpoint', null=True),
        ),
    ]
