# Generated by Django 3.2.8 on 2021-10-23 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0013_boilermodel_shutdown_temp'),
    ]

    operations = [
        migrations.AddField(
            model_name='boilermodel',
            name='shutdown_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
