# Generated by Django 3.2.8 on 2021-10-23 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0014_boilermodel_shutdown_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='analoguethermostatmodel',
            name='serial_num',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AddField(
            model_name='simpleswitchmodel',
            name='serial_num',
            field=models.CharField(default='', max_length=60),
        ),
    ]
