# Generated by Django 3.2.8 on 2021-10-24 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0015_auto_20211023_1913'),
    ]

    operations = [
        migrations.AddField(
            model_name='smartthermostatmodel',
            name='status',
            field=models.CharField(choices=[('ON', 'ON'), ('OFF', 'OFF')], default='OFF', max_length=3),
        ),
    ]
