# Generated by Django 3.2.8 on 2021-10-24 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0016_smartthermostatmodel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='smartthermostatmodel',
            name='last_set_temperature',
            field=models.SmallIntegerField(blank=True, help_text='Field for storing thermostat owner command set temperature value', null=True),
        ),
    ]
