# Generated by Django 3.2.8 on 2021-10-24 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0017_smartthermostatmodel_last_set_temperature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smartthermostatmodel',
            name='last_set_temperature',
            field=models.SmallIntegerField(blank=True, help_text='Field for storing last set temp value before switching off by the owner', null=True),
        ),
    ]
