# Generated by Django 3.2.8 on 2021-10-24 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0018_alter_smartthermostatmodel_last_set_temperature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smartthermostatmodel',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
