# Generated by Django 3.2.8 on 2021-10-25 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0019_alter_smartthermostatmodel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smartthermostatmodel',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
