# Generated by Django 3.2.8 on 2021-10-26 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0020_alter_smartthermostatmodel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='boilermodel',
            name='shutdown_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='boilermodel',
            name='shutdown_enabled',
            field=models.BooleanField(default=False, help_text='Enabled by the '),
        ),
    ]
