# Generated by Django 3.2.8 on 2021-10-26 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0021_auto_20211026_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boilermodel',
            name='shutdown_active',
            field=models.BooleanField(default=False, help_text='If backend logic activated wwsd based on weather API'),
        ),
    ]
