# Generated by Django 3.2.8 on 2021-10-26 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0022_alter_boilermodel_shutdown_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boilermodel',
            name='shutdown_active',
            field=models.BooleanField(default=False, help_text='If the backend logic activated wwsd on its own based on weather API'),
        ),
        migrations.AlterField(
            model_name='boilermodel',
            name='shutdown_enabled',
            field=models.BooleanField(default=False, help_text='Enabled by the property owner'),
        ),
    ]
