# Generated by Django 3.2.8 on 2021-10-27 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0023_auto_20211026_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smartthermostatmodel',
            name='set_temperature',
            field=models.SmallIntegerField(blank=True, default=38, help_text='Field for storing thermostat owner command set temperature value', null=True),
        ),
    ]
