# Generated by Django 3.2.8 on 2021-10-31 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0025_auto_20211030_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensormodel',
            name='pipe',
            field=models.CharField(blank=True, choices=[('SPL', 'Supply'), ('RTN', 'Return')], default='', max_length=3),
        ),
        migrations.AlterField(
            model_name='sensormodel',
            name='type',
            field=models.CharField(choices=[('TMP', 'Temperature'), ('PRS', 'Pressure'), ('CRT', 'Current')], default='', max_length=3),
        ),
    ]
