# Generated by Django 3.2.8 on 2021-10-31 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0026_auto_20211031_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensormodel',
            name='zone_pin',
            field=models.SmallIntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7)], help_text='PIN number used with Controller zone connection', null=True),
        ),
        migrations.AlterField(
            model_name='analoguethermostatmodel',
            name='pin_num',
            field=models.SmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7)], help_text='pin connection index', null=True),
        ),
        migrations.AlterField(
            model_name='sensormodel',
            name='pin_num',
            field=models.SmallIntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7)], help_text='PIN number used with Controller sensor connection', null=True),
        ),
        migrations.AlterField(
            model_name='simpleswitchmodel',
            name='pin_num',
            field=models.SmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7)], help_text='pin connection index', null=True),
        ),
        migrations.AlterField(
            model_name='smartthermostatmodel',
            name='pin_num',
            field=models.SmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7)], help_text='pin connection index', null=True),
        ),
    ]
