# Generated by Django 3.2.9 on 2021-11-03 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0027_auto_20211031_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='smartthermostatmodel',
            name='scheduled_override',
            field=models.BooleanField(default=False),
        ),
    ]
