# Generated by Django 3.2.9 on 2021-11-06 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0028_smartthermostatmodel_scheduled_override'),
    ]

    operations = [
        migrations.AddField(
            model_name='analoguethermostatmodel',
            name='scheduled_override',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='simpleswitchmodel',
            name='scheduled_override',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='analoguethermostatmodel',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='simpleswitchmodel',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
