# Generated by Django 3.2.9 on 2021-11-08 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0029_auto_20211106_0709'),
    ]

    operations = [
        migrations.AddField(
            model_name='ioniqcontrollermodel',
            name='is_master',
            field=models.BooleanField(default=True, help_text='Check this field if this is a master controller. Otherwise, it will be considered as slave'),
        ),
        migrations.AlterField(
            model_name='analoguethermostatmodel',
            name='pin_num',
            field=models.SmallIntegerField(choices=[(1, 1), (2, 2), (3, 3)], help_text='pin connection index', null=True),
        ),
        migrations.AlterField(
            model_name='simpleswitchmodel',
            name='pin_num',
            field=models.SmallIntegerField(choices=[(1, 1), (2, 2), (3, 3)], help_text='pin connection index', null=True),
        ),
    ]
