# Generated by Django 3.2.9 on 2021-11-11 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0030_auto_20211108_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensormodel',
            name='is_system',
            field=models.BooleanField(default=False, help_text='Check this if current sensor installed in the main heating loop'),
        ),
    ]
