# Generated by Django 3.2.9 on 2021-11-16 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0031_sensormodel_is_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='boilermodel',
            name='offhours_setpoint',
            field=models.SmallIntegerField(blank=True, help_text='Set temperature for non-working hours', null=True),
        ),
        migrations.AddField(
            model_name='boilermodel',
            name='vacant_setpoint',
            field=models.SmallIntegerField(blank=True, help_text='Set temperature for non-working hours', null=True),
        ),
    ]
