# Generated by Django 3.2.9 on 2021-11-17 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0032_auto_20211116_0847'),
    ]

    operations = [
        migrations.AddField(
            model_name='boilermodel',
            name='away_mode',
            field=models.BooleanField(default=False, help_text='*Away* mode'),
        ),
    ]
