# Generated by Django 3.2.9 on 2021-11-19 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0033_boilermodel_away_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boilermodel',
            name='offhours_setpoint',
            field=models.SmallIntegerField(blank=True, default=55, help_text='Set temperature for non-working hours', null=True),
        ),
        migrations.AlterField(
            model_name='boilermodel',
            name='shutdown_temp',
            field=models.IntegerField(blank=True, default=55, help_text='Warm weather shutdown setpoint', null=True),
        ),
        migrations.AlterField(
            model_name='boilermodel',
            name='vacant_setpoint',
            field=models.SmallIntegerField(blank=True, default=50, help_text='Set temperature for non-working hours', null=True),
        ),
    ]
