# Generated by Django 3.2.9 on 2021-11-19 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0034_auto_20211119_0534'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boilermodel',
            old_name='away_mode',
            new_name='away_mode_enabled',
        ),
        migrations.AddField(
            model_name='boilermodel',
            name='offhours_active',
            field=models.BooleanField(default=False, help_text='If backend activated offhours according to scheduling'),
        ),
        migrations.AddField(
            model_name='boilermodel',
            name='offhours_enabled',
            field=models.BooleanField(default=False, help_text='Might be enabled by the property owner'),
        ),
        migrations.AlterField(
            model_name='boilermodel',
            name='shutdown_enabled',
            field=models.BooleanField(default=False, help_text='Might be enabled by the property owner'),
        ),
    ]
