# Generated by Django 3.2.9 on 2021-11-21 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0035_auto_20211119_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='boilermodel',
            name='offhours_end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='boilermodel',
            name='offhours_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
