# Generated by Django 3.2.9 on 2021-11-26 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0036_auto_20211121_0649'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boilermodel',
            old_name='offhours_end_time',
            new_name='weekdays_offhours_end_time',
        ),
        migrations.RenameField(
            model_name='boilermodel',
            old_name='offhours_start_time',
            new_name='weekdays_offhours_start_time',
        ),
        migrations.RemoveField(
            model_name='boilermodel',
            name='offhours_setpoint',
        ),
        migrations.AddField(
            model_name='boilermodel',
            name='weekdays_offhours_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='boilermodel',
            name='weekdays_offhours_setpoint',
            field=models.SmallIntegerField(blank=True, default=55, help_text='Set temperature for non-working hours weekend', null=True),
        ),
        migrations.AddField(
            model_name='boilermodel',
            name='weekend_offhours_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='boilermodel',
            name='weekend_offhours_end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='boilermodel',
            name='weekend_offhours_setpoint',
            field=models.SmallIntegerField(blank=True, default=55, help_text='Set temperature for non-working hours weekend', null=True),
        ),
        migrations.AddField(
            model_name='boilermodel',
            name='weekend_offhours_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
