# Generated by Django 3.2.9 on 2021-11-27 19:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0037_auto_20211126_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boilermodel',
            name='weekdays_offhours_end_time',
            field=models.TimeField(blank=True, default=datetime.time(7, 0), null=True),
        ),
        migrations.AlterField(
            model_name='boilermodel',
            name='weekdays_offhours_start_time',
            field=models.TimeField(blank=True, default=datetime.time(19, 0), null=True),
        ),
    ]
