# Generated by Django 3.2.9 on 2021-12-03 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0038_auto_20211127_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='boilermodel',
            name='shower_duration',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='boilermodel',
            name='installation_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
