# Generated by Django 3.2.9 on 2021-12-12 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0039_auto_20211203_0928'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boilermodel',
            name='offhours_active',
        ),
        migrations.RemoveField(
            model_name='boilermodel',
            name='offhours_enabled',
        ),
        migrations.AddField(
            model_name='boilermodel',
            name='forced_endswitch_state',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Turned off'), (1, 'Turned on'), (2, 'Set to auto')], default=2),
        ),
    ]
