# Generated by Django 3.2.9 on 2021-12-29 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0040_auto_20211212_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensormodel',
            name='correction_index',
            field=models.IntegerField(blank=True, help_text='Correction value for sensor reading (positive/negative)', null=True),
        ),
    ]
