# Generated by Django 3.2.9 on 2021-12-29 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0041_sensormodel_correction_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensormodel',
            name='correction_index',
            field=models.IntegerField(blank=True, default=0, help_text='Correction value for sensor reading (positive/negative)', null=True),
        ),
    ]
