# Generated by Django 3.2.9 on 2022-01-01 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0042_alter_sensormodel_correction_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='ioniqcontrollermodel',
            name='systemp_correction_index',
            field=models.IntegerField(blank=True, default=0, help_text='IoniqMini systemp correction index (In case of Max, look for sensor model)', null=True),
        ),
        migrations.AlterField(
            model_name='sensormodel',
            name='correction_index',
            field=models.IntegerField(blank=True, default=0, help_text='Correction value for temperature sensor reading (positive/negative)', null=True),
        ),
    ]
