# Generated by Django 3.2.9 on 2022-01-15 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0043_auto_20220101_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='boilermodel',
            name='cold_pipe_delta_t',
            field=models.PositiveIntegerField(blank=True, help_text='Sets minimum temperature delta value which restrict cold pipe temp drop up to 140 F (i.e. delta_t = 10, minim temp = 150 F', null=True),
        ),
        migrations.AddField(
            model_name='boilermodel',
            name='heating_optmode',
            field=models.BooleanField(default=False, help_text='Enables automated heating cycles correction based on max systemp settings and return pipe min delta'),
        ),
        migrations.AddField(
            model_name='boilermodel',
            name='systemp_limit',
            field=models.PositiveIntegerField(blank=True, help_text='Sets maximum systemp value in F, which will cause endswitch turn off', null=True),
        ),
    ]
