# Generated by Django 4.1.2 on 2022-11-09 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0044_auto_20220115_1554"),
    ]

    operations = [
        migrations.AddField(
            model_name="smartthermostatmodel",
            name="name",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AlterField(
            model_name="boilermodel",
            name="cold_pipe_delta_t",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Sets minimum temperature delta value which restricts cold pipe temp drop up to 140 F (i.e. delta_t = 10, minim temp = 150 F)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="boilermodel",
            name="forced_endswitch_state",
            field=models.PositiveSmallIntegerField(
                choices=[(0, "Turned off"), (1, "Turned on"), (2, "Set to auto")],
                default=2,
                help_text="Affects IoniqMini API only",
            ),
        ),
        migrations.AlterField(
            model_name="boilermodel",
            name="heating_optmode",
            field=models.BooleanField(
                default=False,
                help_text="Enables automated heating cycles optimization, based on max systemp settings and return pipe min delta",
            ),
        ),
    ]
