# Generated by Django 4.1.2 on 2022-11-28 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0045_smartthermostatmodel_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boilermodel',
            name='type',
        ),
    ]
