# Generated by Django 4.1.2 on 2022-11-28 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0046_remove_boilermodel_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='boilermodel',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Steam'), (1, 'Hydronic'), (2, 'Combination')], default=0),
        ),
    ]
