# Generated by Django 3.2.9 on 2021-11-10 12:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportReuquestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(default='', max_length=60)),
                ('request', models.TextField(default='')),
                ('status', models.CharField(choices=[('P', 'Pending'), ('R', 'Resolved'), ('C', 'Closed')], default='P', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_requests', related_query_name='support_request', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Support request',
                'verbose_name_plural': 'Support requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
