# Generated by Django 3.2.9 on 2021-11-10 14:20

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('support', '0002_alter_supportreuquestmodel_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SupportReuquestModel',
            new_name='SupportRequestModel',
        ),
    ]
