# Generated by Django 3.2.8 on 2021-10-12 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('properties', '0001_initial'),
        ('devices', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildingmodel',
            name='owner',
            field=models.ForeignKey(help_text='Property owner', on_delete=django.db.models.deletion.CASCADE, related_name='buildings', related_query_name='building', to='users.ownerprofilemodel'),
        ),
        migrations.AddField(
            model_name='buildingmodel',
            name='provider',
            field=models.ForeignKey(blank=True, help_text='Assigned services provider', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buildings', related_query_name='building', to='users.providerprofilemodel'),
        ),
        migrations.AddField(
            model_name='buildingmodel',
            name='zip_code',
            field=models.ForeignKey(help_text='Property zip code', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buildings', related_query_name='building', to='properties.zipcodemodel'),
        ),
        migrations.AddField(
            model_name='boilerroommodel',
            name='apartment',
            field=models.ForeignKey(blank=True, help_text='Choose apartment if it has a dedicated boiler', null=True, on_delete=django.db.models.deletion.CASCADE, to='properties.buildingmodel'),
        ),
        migrations.AddField(
            model_name='boilerroommodel',
            name='boiler',
            field=models.ForeignKey(blank=True, help_text='Installed boiler', null=True, on_delete=django.db.models.deletion.SET_NULL, to='devices.boilermodel'),
        ),
        migrations.AddField(
            model_name='boilerroommodel',
            name='building',
            field=models.ForeignKey(blank=True, help_text='Choose building if it has only one boiler', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='boiler_rooms', related_query_name='boiler_room', to='properties.buildingmodel'),
        ),
        migrations.AddField(
            model_name='apartmentmodel',
            name='building',
            field=models.ForeignKey(help_text='The building this apartment is a part of', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='apartments', related_query_name='apartment', to='properties.buildingmodel'),
        ),
    ]
