# Generated by Django 3.2.8 on 2021-10-12 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='zipcodemodel',
            options={'ordering': ['-created_at'], 'verbose_name': 'ZIP code', 'verbose_name_plural': 'ZIP codes'},
        ),
    ]
