# Generated by Django 3.2.8 on 2021-10-12 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_alter_zipcodemodel_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boilerroommodel',
            name='apartment',
            field=models.ForeignKey(blank=True, help_text='Choose apartment if it has a dedicated boiler', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='boiler_rooms', related_query_name='boiler_room', to='properties.apartmentmodel'),
        ),
    ]
