# Generated by Django 3.2.8 on 2021-10-13 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_buildingmodel_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zonemodel',
            name='connection_type',
        ),
    ]
