# Generated by Django 3.2.8 on 2021-10-18 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_remove_zonemodel_connection_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zipcodemodel',
            name='todays_temp',
            field=models.IntegerField(blank=True, help_text='Last temperature from weather.gov API in °F', null=True),
        ),
    ]
