# Generated by Django 3.2.8 on 2021-10-20 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0008_simpleswitchmodel'),
        ('properties', '0007_alter_zipcodemodel_todays_temp'),
    ]

    operations = [
        migrations.AddField(
            model_name='roommodel',
            name='analogue_thermostat',
            field=models.ForeignKey(blank=True, help_text='Related analogue thermostat if conneceted', null=True, on_delete=django.db.models.deletion.SET_NULL, to='devices.analoguethermostatmodel'),
        ),
        migrations.AddField(
            model_name='roommodel',
            name='heat_switch',
            field=models.ForeignKey(blank=True, help_text='Related heat-switch if conneceted', null=True, on_delete=django.db.models.deletion.SET_NULL, to='devices.simpleswitchmodel'),
        ),
    ]
