# Generated by Django 3.2.8 on 2021-10-29 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0009_alter_boilerroommodel_boiler'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BoilerRoomModel',
        ),
    ]
