# Generated by Django 3.2.8 on 2021-10-29 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0024_alter_smartthermostatmodel_set_temperature'),
        ('properties', '0010_delete_boilerroommodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartmentmodel',
            name='boiler',
            field=models.OneToOneField(blank=True, help_text='Installed boiler', null=True, on_delete=django.db.models.deletion.SET_NULL, to='devices.boilermodel'),
        ),
        migrations.AddField(
            model_name='buildingmodel',
            name='boiler',
            field=models.OneToOneField(blank=True, help_text='Installed boiler', null=True, on_delete=django.db.models.deletion.SET_NULL, to='devices.boilermodel'),
        ),
    ]
