# Generated by Django 3.2.8 on 2021-10-30 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0024_alter_smartthermostatmodel_set_temperature'),
        ('properties', '0011_auto_20211029_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartmentmodel',
            name='boiler',
            field=models.ForeignKey(blank=True, help_text='Installed boiler', null=True, on_delete=django.db.models.deletion.SET_NULL, to='devices.boilermodel'),
        ),
    ]
