# Generated by Django 3.2.8 on 2021-10-30 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0012_alter_apartmentmodel_boiler'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartmentmodel',
            name='rooms_number',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='buildingmodel',
            name='floors_number',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='roommodel',
            name='heat_source',
            field=models.SmallIntegerField(blank=True, help_text='- Heat source BTU/H', null=True),
        ),
        migrations.AddField(
            model_name='roommodel',
            name='size',
            field=models.SmallIntegerField(blank=True, help_text='Room size in sq ft', null=True),
        ),
    ]
