# Generated by Django 3.2.8 on 2021-10-31 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0013_auto_20211030_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildingmodel',
            name='apartments_number',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
