# Generated by Django 3.2.8 on 2021-10-31 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0014_buildingmodel_apartments_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='zonemodel',
            name='type',
            field=models.CharField(blank=True, choices=[('SPH', 'Space heating'), ('IWH', 'Indirect water heater'), ('RHT', 'Radiant heat')], default='', help_text='Connection type which was set for this zone', max_length=3),
        ),
    ]
