# Generated by Django 3.2.9 on 2021-11-11 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0015_zonemodel_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartmentmodel',
            name='leaseholder',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='apartmentmodel',
            name='max_temp',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apartmentmodel',
            name='min_temp',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
