# Generated by Django 3.2.9 on 2021-11-12 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0016_auto_20211111_0831'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartmentmodel',
            name='is_vacant',
            field=models.BooleanField(default=False),
        ),
    ]
