# Generated by Django 3.2.9 on 2021-11-16 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0017_apartmentmodel_is_vacant'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartmentmodel',
            name='is_alert',
            field=models.BooleanField(default=False, help_text='Checked automatically if was flagged by sysem checks. Details in the related alert model.'),
        ),
        migrations.CreateModel(
            name='ApartmentAlertDetailsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.TextField(default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', related_query_name='alert', to='properties.apartmentmodel')),
            ],
            options={
                'verbose_name': 'Apartment alerts',
                'verbose_name_plural': 'Apartment alert',
                'ordering': ['-created_at'],
            },
        ),
    ]
