# Generated by Django 3.2.9 on 2021-11-17 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0032_auto_20211116_0847'),
        ('properties', '0018_auto_20211116_0847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartmentmodel',
            name='boiler',
            field=models.ForeignKey(blank=True, help_text='Installed boiler', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='apartments', related_query_name='apartment', to='devices.boilermodel'),
        ),
        migrations.AlterField(
            model_name='buildingmodel',
            name='boiler',
            field=models.OneToOneField(blank=True, help_text='Installed boiler', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buildings', related_query_name='building', to='devices.boilermodel'),
        ),
    ]
