# Generated by Django 3.2.9 on 2021-11-19 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0019_auto_20211117_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='roommodel',
            name='room_type',
            field=models.CharField(choices=[('LR', 'Living room'), ('BR', 'Bedroom'), ('DR', 'Dining'), ('GA', 'Garage'), ('KT', 'Kitchen'), ('BT', 'Bathroom'), ('GR', 'Guest room'), ('KR', "Kid's room"), ('OF', 'Office'), ('OT', 'Other')], default='', max_length=2),
        ),
    ]
