# Generated by Django 3.2.9 on 2021-11-19 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0020_roommodel_room_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartmentmodel',
            name='tlimits_is_on',
            field=models.BooleanField(default=False, help_text="If enabled, tenants won't be able to set their thermostat outside of landlord range"),
        ),
    ]
