# Generated by Django 3.2.9 on 2022-01-13 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0021_apartmentmodel_tlimits_is_on'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherRecordModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('zip_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='temperatures', related_query_name='temperature', to='properties.zipcodemodel')),
            ],
            options={
                'verbose_name': 'Temperature record',
                'verbose_name_plural': 'Temperature records',
            },
        ),
    ]
