# Generated by Django 3.2.9 on 2022-01-13 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0022_weatherrecordmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='weatherrecordmodel',
            name='temp',
            field=models.IntegerField(blank=True, help_text='Temp value from weather.gov API in °F', null=True),
        ),
    ]
