# Generated by Django 3.2.9 on 2022-01-15 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0024_auto_20220113_1405'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weatherrecordmodel',
            options={'ordering': ['-created_at'], 'verbose_name': 'Temperature record', 'verbose_name_plural': 'Temperature records'},
        ),
    ]
