# Generated by Django 3.2.9 on 2021-11-03 10:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deviceschedulemodel',
            name='checkpoint',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 1, 0, 0), help_text='Primary timestamp for scheduled execution'),
        ),
    ]
