# Generated by Django 3.2.9 on 2021-11-03 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0002_alter_deviceschedulemodel_checkpoint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deviceschedulemodel',
            name='checkpoint',
            field=models.DateTimeField(help_text='Primary timestamp for scheduled execution'),
        ),
    ]
