# Generated by Django 3.2.9 on 2021-11-03 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0003_alter_deviceschedulemodel_checkpoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='thermostatsubscribermodel',
            name='setpoint',
            field=models.SmallIntegerField(help_text='Value to override smart thermostat setpoint field', null=True),
        ),
    ]
