# Generated by Django 3.2.9 on 2021-11-03 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0004_thermostatsubscribermodel_setpoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceschedulemodel',
            name='week_day',
            field=models.CharField(choices=[('MO', 'Monday'), ('TU', 'Tuesday'), ('WE', 'Wednesday'), ('TH', 'Thursday'), ('FR', 'Friday'), ('SA', 'Saturday'), ('SU', 'Sunday')], default='MO', max_length=2),
        ),
    ]
