# Generated by Django 3.2.9 on 2021-11-03 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_tenantprofilemodel_password_reset_needed'),
        ('schedules', '0006_alter_deviceschedulemodel_week_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='thermostatsubscribermodel',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedules', related_query_name='schedule', to='users.ownerprofilemodel'),
        ),
    ]
