# Generated by Django 3.2.9 on 2021-11-04 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0028_smartthermostatmodel_scheduled_override'),
        ('schedules', '0007_thermostatsubscribermodel_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thermostatsubscribermodel',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribers', related_query_name='subscriber', to='schedules.deviceschedulemodel'),
        ),
        migrations.AlterField(
            model_name='thermostatsubscribermodel',
            name='thermostat',
            field=models.ForeignKey(help_text='Smart thermostat which should be updated', on_delete=django.db.models.deletion.CASCADE, to='devices.smartthermostatmodel'),
        ),
    ]
