# Generated by Django 3.2.9 on 2021-11-06 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0028_smartthermostatmodel_scheduled_override'),
        ('users', '0012_customuser_updated_at'),
        ('schedules', '0009_alter_deviceschedulemodel_week_day'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeatSwitchSubscriberModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True, help_text='Heat switch status to set')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='heatswitch_schedules', related_query_name='heatswitch_schedules', to='users.ownerprofilemodel')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heat_switches', related_query_name='heat_switch', to='schedules.deviceschedulemodel')),
                ('switch', models.ForeignKey(help_text='Heat switch which should be updated', on_delete=django.db.models.deletion.CASCADE, to='devices.simpleswitchmodel')),
            ],
            options={
                'verbose_name': 'Heatswitch subscriber',
                'verbose_name_plural': 'Heatswitch subscribers',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='AnalogueThermostatSubscriberModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True, help_text='Analogue thermostat status to set')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('analogue_thermostat', models.ForeignKey(help_text='Analogue thermostat which should be updated', on_delete=django.db.models.deletion.CASCADE, to='devices.analoguethermostatmodel')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analogue_schedules', related_query_name='analogue_schedules', to='users.ownerprofilemodel')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analogue_switches', related_query_name='analogue_switch', to='schedules.deviceschedulemodel')),
            ],
            options={
                'verbose_name': 'Heatswitch subscriber',
                'verbose_name_plural': 'Heatswitch subscribers',
                'ordering': ['-updated_at'],
            },
        ),
    ]
