# Generated by Django 3.2.9 on 2021-11-06 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0010_analoguethermostatsubscribermodel_heatswitchsubscribermodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analoguethermostatsubscribermodel',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Analogue subscriber', 'verbose_name_plural': 'Analogue subscribers'},
        ),
    ]
