# Generated by Django 3.2.9 on 2021-11-24 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0036_auto_20211121_0649'),
        ('users', '0012_customuser_updated_at'),
        ('schedules', '0011_alter_analoguethermostatsubscribermodel_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandlordOffHoursScheduleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_checkpoint', models.DateTimeField(help_text='Offhours start timestamp')),
                ('end_checkpoint', models.DateTimeField(help_text='Offhours end timestamp')),
                ('weekend', models.BooleanField(default=False, help_text='Weekdays or Weekend')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('boiler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offhours_schedule', related_query_name='offhours_schedules', to='devices.boilermodel')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.ownerprofilemodel')),
            ],
            options={
                'verbose_name': 'Landlord off-hours schedule',
                'verbose_name_plural': 'Landlord off-hours schedules',
                'ordering': ['owner'],
            },
        ),
    ]
