# Generated by Django 3.2.9 on 2021-11-24 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0012_landlordoffhoursschedulemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='landlordoffhoursschedulemodel',
            name='setpoint',
            field=models.SmallIntegerField(help_text='Value to override smart thermostat setpoint field', null=True),
        ),
    ]
