# Generated by Django 3.2.9 on 2021-11-25 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0013_landlordoffhoursschedulemodel_setpoint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landlordoffhoursschedulemodel',
            name='end_checkpoint',
            field=models.TimeField(help_text='Offhours end timestamp'),
        ),
        migrations.AlterField(
            model_name='landlordoffhoursschedulemodel',
            name='start_checkpoint',
            field=models.TimeField(help_text='Offhours start Fieldstamp'),
        ),
    ]
