# Generated by Django 3.2.9 on 2021-11-26 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0014_auto_20211125_1003'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LandlordOffHoursScheduleModel',
        ),
    ]
