# Generated by Django 4.1.7 on 2023-02-28 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0025_alter_weatherrecordmodel_options'),
        ('users', '0012_customuser_updated_at'),
        ('schedules', '0015_delete_landlordoffhoursschedulemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZoneSubscriberModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setpoint', models.SmallIntegerField(help_text='Value to override smart thermostat setpoint field', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('heating_zone', models.ForeignKey(help_text='Smart thermostat which should be updated', on_delete=django.db.models.deletion.CASCADE, to='properties.zonemodel')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='zone_schedules', related_query_name='zone_schedule', to='users.ownerprofilemodel')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', related_query_name='zone', to='schedules.deviceschedulemodel')),
            ],
            options={
                'verbose_name': 'Heating zone subscriber',
                'verbose_name_plural': 'Heating zones subscribers',
                'ordering': ['-updated_at'],
            },
        ),
    ]
